# Generated by Django 4.2.1 on 2023-06-27 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0004_alter_task_id_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id_member',
        ),
        migrations.AddField(
            model_name='task',
            name='id_member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
