# Generated by Django 4.2.1 on 2023-06-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_remove_task_id_member_task_id_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='id_member',
            new_name='member',
        ),
    ]
