# Generated by Django 4.2.1 on 2023-06-27 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0006_rename_id_member_task_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='member',
        ),
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
