# Generated by Django 4.2.1 on 2023-06-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_remove_task_member_task_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
