# Generated by Django 4.2.1 on 2023-07-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_post_likes_post_content_post_likes1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes1',
            new_name='likes',
        ),
    ]
